export const categoriesData = [
  { id: 1, name: "🌕 전체" },
  { id: 2, name: "📡 중개 플랫폼" },
  { id: 3, name: "📷 라이프스타일" },
  { id: 4, name: "⌚️ 하드웨어" },
  { id: 5, name: "💰 금융" },
  { id: 6, name: "👫 소셜" },
  { id: 7, name: "🎙 미디어" },
  { id: 8, name: "✏️ 교육" },
  { id: 9, name: "🚲 생산성" },
  { id: 10, name: "🔗 블록체인" },
  { id: 11, name: "💻 노코드" },
  { id: 12, name: "🤖 인공지능" },
  { id: 13, name: "🏘 커뮤니티" },
  { id: 14, name: "📊 분석툴" },
  { id: 15, name: "🎨 디자인" },
  { id: 16, name: "🔮 마케팅툴" },
  { id: 17, name: "👟 소비재 브랜드" },
  { id: 18, name: "💳 이커머스" },
];

export const productsData = [
  {
    id: 1,
    userName: "해리",
    productTitle: "넥스트 유니콘",
    desc: "투자자와 창업자 중개 플랫폼",
    upvote: "32",
    category: "📡 중개 플랫폼",
    comment: "43",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 2,
    userName: "론위즐리",
    productTitle: "Webflow",
    desc: "노코드 웹사이트 빌더",
    upvote: "12",
    category: "📡 노코드",
    comment: "43",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 3,
    userName: "헤르미온느",
    productTitle: "Product Hunt",
    desc: "프로덕트 디스커버리 사이트",
    upvote: "32",
    category: "🏘 커뮤니티",
    comment: "43",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 4,
    userName: "해그리드",
    productTitle: "Hackers News",
    desc: "해커들을 위한 게시판",
    upvote: "32",
    category: "🏘 커뮤니티",
    comment: "33",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 5,
    userName: "덤블도어",
    productTitle: "Loom",
    desc: "비디오 메세징 툴",
    upvote: "11",
    category: "🚲 생산성",
    comment: "63",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 6,
    userName: "프로도",
    productTitle: "Pinterest",
    desc: "인터넷에 있는 영감들을 수집하는 플랫폼",
    upvote: "100",
    category: "👫 소셜",
    comment: "15",
    tnImage: "",
    avatarImage: "",
  },
  {
    id: 7,
    userName: "레골라스",
    productTitle: "Facebook",
    desc: "친구들, 가족들과 연결할 수 있는 소셜네트워크",
    upvote: "8",
    category: "👫 소셜",
    comment: "3",
    tnImage: "",
    avatarImage: "",
  },
];
